export {default as FooterComponent} from '~/components/common/FooterComponent'
export {default as HeaderComponent} from '~/components/common/HeaderComponent'
export {default as Logo} from '~/components/common/Logo'
export {default as LogoWithWhiteBorders} from '~/components/common/LogoWhiteBorders'
export {default as SmallTomato} from '~/components/common/SmallTomato'
